using System.Collections.Generic;

namespace NFSRaider.GeneratedStrings.PartsLists.ProStreet
{
    public static class Exhausts
    {
        public static readonly List<string> List = new List<string>() 
        {
"EXHAUST_KIT00_CENTER_LEVEL1",
"EXHAUST_KIT01_CENTER_LEVEL1",
"EXHAUST_KIT02_CENTER_LEVEL1",
"EXHAUST_KIT03_CENTER_LEVEL1",
"EXHAUST_KIT04_CENTER_LEVEL1",
"EXHAUST_KIT05_CENTER_LEVEL1",
"EXHAUST_KIT06_CENTER_LEVEL1",
"EXHAUST_KIT07_CENTER_LEVEL1",
"EXHAUST_KIT08_CENTER_LEVEL1",
"EXHAUST_KIT09_CENTER_LEVEL1",
"EXHAUST_KIT10_CENTER_LEVEL1",
"EXHAUST_KIT11_CENTER_LEVEL1",
"EXHAUST_KIT12_CENTER_LEVEL1",
"EXHAUST_KIT13_CENTER_LEVEL1",
"EXHAUST_KIT14_CENTER_LEVEL1",
"EXHAUST_KIT15_CENTER_LEVEL1",
"EXHAUST_KIT00_LEVEL1",
"EXHAUST_KIT01_LEVEL1",
"EXHAUST_KIT02_LEVEL1",
"EXHAUST_KIT03_LEVEL1",
"EXHAUST_KIT04_LEVEL1",
"EXHAUST_KIT05_LEVEL1",
"EXHAUST_KIT06_LEVEL1",
"EXHAUST_KIT07_LEVEL1",
"EXHAUST_KIT08_LEVEL1",
"EXHAUST_KIT09_LEVEL1",
"EXHAUST_KIT10_LEVEL1",
"EXHAUST_KIT11_LEVEL1",
"EXHAUST_KIT12_LEVEL1",
"EXHAUST_KIT13_LEVEL1",
"EXHAUST_KIT14_LEVEL1",
"EXHAUST_KIT15_LEVEL1",
        };
    }
}
