using System.Collections.Generic;

namespace NFSRaider.MainKeys.PartsLists.ProStreet
{
    public static class Brakes
    {
        public static readonly List<string> List = new List<string>() 
        {
"BRAKE_KIT01_BRAKE_FRONT",
"BRAKE_KIT02_BRAKE_FRONT",
"BRAKE_KIT03_BRAKE_FRONT",
"BRAKE_KIT04_BRAKE_FRONT",
"BRAKE_KIT05_BRAKE_FRONT",
"BRAKE_KIT06_BRAKE_FRONT",
"BRAKE_KIT07_BRAKE_FRONT",
"BRAKE_KIT08_BRAKE_FRONT",
"BRAKE_KIT09_BRAKE_FRONT",
"BRAKE_KIT10_BRAKE_FRONT",
"BRAKE_KIT11_BRAKE_FRONT",
"BRAKE_KIT12_BRAKE_FRONT",
"BRAKE_KIT13_BRAKE_FRONT",
"BRAKE_KIT14_BRAKE_FRONT",
"BRAKE_KIT15_BRAKE_FRONT",
"BRAKE_KIT01_BRAKE_REAR",
"BRAKE_KIT02_BRAKE_REAR",
"BRAKE_KIT03_BRAKE_REAR",
"BRAKE_KIT04_BRAKE_REAR",
"BRAKE_KIT05_BRAKE_REAR",
"BRAKE_KIT06_BRAKE_REAR",
"BRAKE_KIT07_BRAKE_REAR",
"BRAKE_KIT08_BRAKE_REAR",
"BRAKE_KIT09_BRAKE_REAR",
"BRAKE_KIT10_BRAKE_REAR",
"BRAKE_KIT11_BRAKE_REAR",
"BRAKE_KIT12_BRAKE_REAR",
"BRAKE_KIT13_BRAKE_REAR",
"BRAKE_KIT14_BRAKE_REAR",
"BRAKE_KIT15_BRAKE_REAR",
        };
    }
}
