using System.Collections.Generic;

namespace NFSRaider.MainKeys.PartsLists.ProStreet
{
    public static class PaintGroups
    {
        public static readonly List<string> List = new List<string>()
        {
"WHEEL_PAINT_GROUP_KIT00_METALLIC",
"WHEEL_PAINT_GROUP_KIT00_CHROME",
"WHEEL_PAINT_GROUP_KIT00_MATTE",
"WINDOW_TINT_GROUP_KIT00_LIGHT",
"WINDOW_TINT_GROUP_KIT00_DARK",
"WINDOW_TINT_GROUP_KIT00_PEARL",
"BODY_PAINT_GROUP_KIT00_GLOSS",
"BODY_PAINT_GROUP_KIT00_METALLIC",
"BODY_PAINT_GROUP_KIT00_MATTE",
"BODY_PAINT_GROUP_KIT00_PEARL",
"BODY_PAINT_GROUP_KIT00_CHROME",
"BODY_PAINT_GROUP_KIT00_CANDY",
"BODY_PAINT_GROUP_KIT00_IRIDESCENT",
"ROLLCAGE_PAINT_GROUP_KIT00_METALLIC",
"ROLLCAGE_PAINT_GROUP_KIT00_CHROME",
"ROLLCAGE_PAINT_GROUP_KIT00_MATTE",
        };
    }
}
