using System.Collections.Generic;

namespace NFSRaider.GeneratedStrings.Materials
{
    public static class Typos
    {
        public static readonly List<string> List = new List<string>
        {
"ALUMIUM",
"BADGING",
"BOTOM",
"BRAKELIGHTGLASSS",
"BRAKELIGHTREFLECTOR",
"BRAKELIGHTS",
"BRALELIGHT",
"BREAKLIGHT",
"CAARBONFIBER",
"CARBON",
"CARBONFIBRE2",
"CARKSIN",
"CARSKIMA",
"CHOME",
"CRHOME",
"CROME",
"DULLLPLASTIC",
"DULLPALSTIC",
"DULLPASTIC",
"DULLPLASTIAK",
"DULLPLSTIC",
"DULPLASTIC",
"HEADLIGHGLASS",
"HEADLIGHSAGLASS",
"HEADLIGHSAREFLECTOR",
"HEADLIGHTFLECTOR",
"HEADLIGHTREFLESTOR",
"HEADLLIGHTREFLECTOR",
"HEADREFLECTOR",
"HEALIGHT",
"LAINNOTHING",
"MAGCHORME",
"MAGCRHOME",
"MAGSILVER3",
"MOLDNGS",
"MUGCHROME",
"PLAINNOTHINEK",
"PLAINNOTHINFH",
"PLAINNOTHING]",
"PLAINNOTHNG",
"PLAINNOTING",
"PLAINNTOHING",
"PLAINOTHING",
"PLASTIC",
"SHIELD",
"WIINDSHIELD",
        };
    }
}
