using System.Collections.Generic;

namespace NFSRaider.GeneratedStrings.Tracks.SceneryGroups
{
    public static class Carbon
    {
        public static readonly List<string> List = new List<string>
        {
"SCENERY_GROUP_CTA1",
"SCENERY_GROUP_CTA2",
"SCENERY_GROUP_CTB1",
"SCENERY_GROUP_CTB2",
"SCENERY_GROUP_CTC1",
"SCENERY_GROUP_CTC2",
"SCENERY_GROUP_CTD1",
"SCENERY_GROUP_CTD2",
"SCENERY_GROUP_CTE1",
"SCENERY_GROUP_CTE2",
"SCENERY_GROUP_EX1",
"SCENERY_GROUP_EX2",
"SCENERY_GROUP_EX3",
"SCENERY_GROUP_Extra1",
"SCENERY_GROUP_Extra2",
"SCENERY_GROUP_Extra3",
"SCENERY_GROUP_MUA1",
"SCENERY_GROUP_MUA2",
"SCENERY_GROUP_MUB1",
"SCENERY_GROUP_MUB2",
"SCENERY_GROUP_TNB1",
"SCENERY_GROUP_TNB2",
"SCENERY_GROUP_TNC1",
"SCENERY_GROUP_TNC2",
"SCENERY_GROUP_TN_2_2",
"SCENERY_GROUP_TN_4_3",
"SCENERY_GROUP_TN_5_3",
        };
    }
}
