using System.Collections.Generic;

namespace NFSRaider.MainKeys.PartsLists.Underground1
{
    public static class WindowTint
    {
        public static readonly List<string> List = new List<string>()
        {
"WINDOW_TINT_STOCK",
"WINDSHIELD_TINT_L1_BLACK",
"WINDSHIELD_TINT_L1_GREEN",
"WINDSHIELD_TINT_L2_BLACK",
"WINDSHIELD_TINT_L2_GREEN",
"WINDSHIELD_TINT_L2_BLUE",
"WINDSHIELD_TINT_L2_RED",
"WINDSHIELD_TINT_L3_BLACK",
"WINDSHIELD_TINT_L3_GREEN",
"WINDSHIELD_TINT_L3_BLUE",
"WINDSHIELD_TINT_L3_RED",
"WINDSHIELD_TINT_L3_YELLOW",
"WINDSHIELD_TINT_L3_AQUA",
"WINDSHIELD_TINT_L3_GRAPE",
"WINDSHIELD_TINT_L3_ORANGE",
"WINDSHIELD_TINT_L3_PINK",
"WINDSHIELD_TINT_L3_LIME",
"WINDSHIELD_TINT_L3_LAVENDER",
"WINDSHIELD_TINT_L3_GOLD",
        };
    }
}
