using System.Collections.Generic;

namespace NFSRaider.GeneratedStrings.PartsLists.Underground2
{
    public static class WindowTint
    {
        public static readonly List<string> List = new List<string>()
        {
"WINDOW_TINT_STOCK",
"WINDSHIELD_TINT_L1_BLACK",
"WINDSHIELD_TINT_L1_GREEN",
"WINDSHIELD_TINT_L1_MED_BLACK",
"WINDSHIELD_TINT_L1_MED_GREEN",
"WINDSHIELD_TINT_L1_BLUE",
"WINDSHIELD_TINT_L1_RED",
"WINDSHIELD_TINT_L2_BLACK",
"WINDSHIELD_TINT_L2_GREEN",
"WINDSHIELD_TINT_L2_BLUE",
"WINDSHIELD_TINT_L2_RED",
"WINDSHIELD_TINT_L2_YELLOW",
"WINDSHIELD_TINT_L2_AQUA",
"WINDSHIELD_TINT_L2_GRAPE",
"WINDSHIELD_TINT_L2_ORANGE",
"WINDSHIELD_TINT_L2_PINK",
"WINDSHIELD_TINT_L2_LIME",
"WINDSHIELD_TINT_L2_LAVENDER",
"WINDSHIELD_TINT_L2_GOLD",
"WINDSHIELD_TINT_L3_PEARL BLACK",
"WINDSHIELD_TINT_L3_PEARL GREEN",
"WINDSHIELD_TINT_L3_PEARL BLUE",
"WINDSHIELD_TINT_L3_PEARL RED",
"WINDSHIELD_TINT_L3_PEARL YELLOW",
"WINDSHIELD_TINT_L3_PEARL AQUA",
"WINDSHIELD_TINT_L3_PEARL GRAPE",
"WINDSHIELD_TINT_L3_PEARL ORANGE",
"WINDSHIELD_TINT_L3_PEARL PINK",
"WINDSHIELD_TINT_L3_PEARL LIME",
"WINDSHIELD_TINT_L3_PEARL LAVENDER",
"WINDSHIELD_TINT_L3_PEARL GOLD",
        };
    }
}
