using System.Collections.Generic;

namespace NFSRaider.Keys.MainKeys.PartsLists.ProStreet
{
    public static class BrakeRotor
    {
        public static readonly List<string> List = new List<string>()
        {
"BRAKE_KIT01_BRAKEROTOR_FRONT",
"BRAKE_KIT02_BRAKEROTOR_FRONT",
"BRAKE_KIT03_BRAKEROTOR_FRONT",
"BRAKE_KIT04_BRAKEROTOR_FRONT",
"BRAKE_KIT05_BRAKEROTOR_FRONT",
"BRAKE_KIT06_BRAKEROTOR_FRONT",
"BRAKE_KIT07_BRAKEROTOR_FRONT",
"BRAKE_KIT08_BRAKEROTOR_FRONT",
"BRAKE_KIT09_BRAKEROTOR_FRONT",
"BRAKE_KIT10_BRAKEROTOR_FRONT",
"BRAKE_KIT11_BRAKEROTOR_FRONT",
"BRAKE_KIT12_BRAKEROTOR_FRONT",
"BRAKE_KIT13_BRAKEROTOR_FRONT",
"BRAKE_KIT14_BRAKEROTOR_FRONT",
"BRAKE_KIT15_BRAKEROTOR_FRONT",
"BRAKE_KIT01_BRAKEROTOR_REAR",
"BRAKE_KIT02_BRAKEROTOR_REAR",
"BRAKE_KIT03_BRAKEROTOR_REAR",
"BRAKE_KIT04_BRAKEROTOR_REAR",
"BRAKE_KIT05_BRAKEROTOR_REAR",
"BRAKE_KIT06_BRAKEROTOR_REAR",
"BRAKE_KIT07_BRAKEROTOR_REAR",
"BRAKE_KIT08_BRAKEROTOR_REAR",
"BRAKE_KIT09_BRAKEROTOR_REAR",
"BRAKE_KIT10_BRAKEROTOR_REAR",
"BRAKE_KIT11_BRAKEROTOR_REAR",
"BRAKE_KIT12_BRAKEROTOR_REAR",
"BRAKE_KIT13_BRAKEROTOR_REAR",
"BRAKE_KIT14_BRAKEROTOR_REAR",
"BRAKE_KIT15_BRAKEROTOR_REAR",
        };
    }
}
