using System.Collections.Generic;

namespace NFSRaider.Keys.MainKeys.PartsLists.MostWanted
{
    public static class Spoilers
    {
        public static readonly List<string> List = new List<string>()
        {
"SPOILER_STYLE01",
"SPOILER_STYLE02",
"SPOILER_STYLE03",
"SPOILER_STYLE04",
"SPOILER_STYLE05",
"SPOILER_STYLE06",
"SPOILER_STYLE07",
"SPOILER_STYLE08",
"SPOILER_STYLE09",
"SPOILER_STYLE10",
"SPOILER_STYLE11",
"SPOILER_STYLE13",
"SPOILER_STYLE15",
"SPOILER_STYLE16",
"SPOILER_STYLE17",
"SPOILER_STYLE18",
"SPOILER_STYLE26",
"SPOILER_STYLE27",
"SPOILER_STYLE28",
"SPOILER_STYLE29",
"SPOILER_STYLE30",
"SPOILER_STYLE31",
"SPOILER_STYLE34",
"SPOILER_STYLE36",
"SPOILER_STYLE38",
"SPOILER_STYLE40",
"SPOILER_STYLE41",
"SPOILER_STYLE42",
"SPOILER_STYLE43",
"SPOILER_STYLE44",
        };
    }
}
